<div style="text-align: center; background: linear-gradient(135deg, #e8d5f5, #d0e8fb); border-radius: 16px; padding: 40px 30px; font-family: 'Times New Roman', Times, serif;">

  <p style="font-size: 20px; font-weight: bold; color: #6c3483; letter-spacing: 4px; margin: 0;">
    LECTURE 02
  </p>

  <h1 style="font-size: 44px; font-weight: bold; color: #2c3e50; margin: 12px 0;">
    Introduction to NumPy
  </h1>

  <p style="font-size: 18px; font-weight: bold; color: #444; margin-top: 15px;">
    Numerical Computing with Python, Arrays, Shapes, and Operations
  </p>

  <p style="font-size: 17px; color: #555; margin-top: 25px;">
    Presented by
  </p>
  <p style="font-size: 22px; font-weight: bold; color: #2c3e50; margin: 4px 0;">
    Dr. Jamshaid Ul Rahman
  </p>
  <p style="font-size: 16px; color: #666; margin: 4px 0;">
    Assistant Professor, ASSMS GCU Lahore
  </p>

</div>

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 28px; margin: 0 0 10px 0;">Introduction to NumPy</h2><p style="font-size: 18px; font-weight: bold; color: #6c3483; margin: 0 0 15px 0;">NumPy means Numerical Python</p><ul style="font-size: 16px; color: #333; line-height: 2;"><li>A general purpose array processing package, used for working with arrays</li><li>The core library for scientific computing in Python</li><li>Provides a high performance multidimensional array object</li><li>Offers tools for working with these arrays efficiently</li><li>To use NumPy, we first need to import it into our program</li></ul></div>

In [1]:
import numpy as np

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 35px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 28px; margin: 0 0 20px 0;">Arrays, Dimension and Shape</h2><p style="font-size: 20px; font-weight: bold; color: #6c3483; margin: 0 0 6px 0;">Arrays</p><p style="font-size: 17px; color: #333; margin: 0 0 20px 0;">A NumPy array is a grid of values, all of the same type. It is the central data structure of the NumPy library.</p><p style="font-size: 20px; font-weight: bold; color: #2980b9; margin: 0 0 6px 0;">Dimension</p><p style="font-size: 17px; color: #333; margin: 0 0 20px 0;">The number of dimensions is called the rank of the array.</p><p style="font-size: 20px; font-weight: bold; color: #c2185b; margin: 0 0 6px 0;">Shape</p><p style="font-size: 17px; color: #333; margin: 0;">The shape of an array is a tuple of integers giving the size of the array along each dimension.</p></div>

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 26px; margin: 0 0 15px 0;">NumPy Array Attributes</h2><p style="font-size: 16px; color: #333; margin-bottom: 15px;">In NumPy, attributes are the properties of arrays that provide information about the array's shape, size, datatype, dimension and so on. There are numerous attributes available, some of which are listed below.</p><table style="width: 100%; border-collapse: collapse; font-size: 15px; color: #333;"><tr style="background-color: #e0d0f5;"><th style="text-align: left; padding: 10px; border-bottom: 2px solid #6c3483; color: #2c3e50;">Attribute</th><th style="text-align: left; padding: 10px; border-bottom: 2px solid #6c3483; color: #2c3e50;">Description</th><th style="text-align: left; padding: 10px; border-bottom: 2px solid #6c3483; color: #2c3e50;">Syntax</th></tr><tr><td style="padding: 10px; font-family: monospace; color: #6c3483; font-weight: bold;">ndim</td><td style="padding: 10px;">Returns the dimension (total number of axes) of the array</td><td style="padding: 10px; font-family: monospace;">arr.ndim</td></tr><tr style="background-color: #faf6ff;"><td style="padding: 10px; font-family: monospace; color: #6c3483; font-weight: bold;">size</td><td style="padding: 10px;">Returns the number of elements in the array</td><td style="padding: 10px; font-family: monospace;">arr.size</td></tr><tr><td style="padding: 10px; font-family: monospace; color: #6c3483; font-weight: bold;">dtype</td><td style="padding: 10px;">Returns the datatype of the elements in the array</td><td style="padding: 10px; font-family: monospace;">arr.dtype</td></tr><tr style="background-color: #faf6ff;"><td style="padding: 10px; font-family: monospace; color: #6c3483; font-weight: bold;">shape</td><td style="padding: 10px;">Returns a tuple of sizes of each dimension</td><td style="padding: 10px; font-family: monospace;">arr.shape</td></tr></table></div>

In [1]:
import numpy as np


In [2]:
arr=np.array([[1,2],[3,4],[1,4]])
arr1=np.array([[[1,2,3,4]],[[1,2,4,0]]])
arr2=np.array([[[1,2]],[[3,4]]])



In [3]:
print('array1',arr1)
print('arrayshape',arr1.shape)
print('arr2dimension',arr2.ndim)
print('size',arr2.size)
print(arr1.ndim)
print(arr2.shape)

array1 [[[1 2 3 4]]

 [[1 2 4 0]]]
arrayshape (2, 1, 4)
arr2dimension 3
size 4
3
(2, 1, 2)


In [4]:
 arr4=np.array([[1,2,3,4],[5,6,7,8]])
print('dimension=',arr4.ndim,'\n','type=',arr4.dtype)

dimension= 2 
 type= int32


In [5]:
arr5=np.array([1,2,3,4,5])
print("Third element=",arr5[2])
arr5[2]=11
print(arr5)

Third element= 3
[ 1  2 11  4  5]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 26px; margin: 0 0 15px 0;">Data Types</h2><p style="font-size: 16px; color: #333; margin-bottom: 15px;">The data type of an array determines the type of elements it holds and how they are stored in memory.</p><ul style="font-size: 16px; color: #333; line-height: 2;"><li><strong style="color: #6c3483;">Integer type</strong> (int)</li><li><strong style="color: #2980b9;">Unsigned Integer type</strong> (uint)</li><li><strong style="color: #c2185b;">Float type</strong> (float)</li><li><strong style="color: #16a085;">String type</strong> (str, unicode)</li><li><strong style="color: #d35400;">Boolean type</strong> (bool)</li><li><strong style="color: #8e44ad;">Complex type</strong> (complex)</li><li><strong style="color: #34495e;">Object type</strong> (object)</li></ul></div>

In [7]:
int_arr=np.array([1,5,6,7,2])
print(int_arr.dtype)
print("__________")
float_arr=np.array([1.1, 2.2, 3.3, 4.4, 5.5])
print(float_arr.dtype)
print("__________")
complex_arr=np.array([1+2j, 3+4j, 5+6j])
print(complex_arr.dtype)
print("__________")
bool_arr=np.array([True, False, True, False])
print(bool_arr.dtype)
print("__________")
str_arr=np.array(['uzma'])
print(str_arr.dtype)
print("__________")
#Create a 1D array with mixed data types
mixed_arr = np.array([1, "hello", 3.14], dtype=object)
print(mixed_arr)
print(mixed_arr.dtype)

int32
__________
float64
__________
complex128
__________
bool
__________
<U4
__________
[1 'hello' 3.14]
object


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 10px 0;">Shape of Array</h2><p style="font-size: 16px; color: #333; margin: 0;">Number of elements in each dimension.</p></div>

In [8]:
import numpy as np
a=np.array([[1,2],[3,5]])
print('arrayshape',a.shape)

arrayshape (2, 2)


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 10px 0;">Reshape of an Array</h2><p style="font-size: 16px; color: #333; margin: 6px 0;">Reshaping means changing the shape of an array. It gives a new shape to an array without changing its data.</p><p style="font-size: 16px; color: #333; margin: 6px 0;">The shape of an array is the number of elements in each dimension.</p><p style="font-size: 16px; color: #333; margin: 6px 0;">By reshaping, we can add or remove dimensions, or change the number of elements in each dimension.</p></div>

In [9]:
import numpy as np
a2=np.array([1,2,3,5,7,8,9,0])
print(a2.ndim)
a3=a2.reshape(2,4)
print('a3=',a3,'\n','a3dim=',a3.ndim,'\n','type=',a3.dtype)


1
a3= [[1 2 3 5]
 [7 8 9 0]] 
 a3dim= 2 
 type= int32


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 10px 0;">Reshape from 1D to 3D</h2><p style="font-size: 16px; color: #333; margin: 6px 0 15px 0;">We can reshape an 8 element 1D array into a 2D array of 4 elements in 2 rows, but we cannot reshape it into a 2D array of 3 elements in 3 rows, since that would require 3 times 3 equals 9 elements.</p><p style="font-size: 17px; color: #6c3483; font-weight: bold; margin: 15px 0 6px 0;">3D Array</p><p style="font-size: 16px; color: #333; margin: 0 0 12px 0;">A three dimensional array in C is a collection of two dimensional arrays.</p><p style="font-family: monospace; background-color: #e0d0f5; color: #2c3e50; padding: 8px 12px; border-radius: 6px; display: inline-block; font-size: 15px;">data_type array_name[x][y][z];</p><ul style="font-size: 16px; color: #333; line-height: 2; margin-top: 15px;"><li><strong style="color: #6c3483;">data_type:</strong> type of data to be stored in each element</li><li><strong style="color: #2980b9;">array_name:</strong> name of the array</li><li><strong style="color: #c2185b;">X:</strong> number of 2D arrays</li><li><strong style="color: #16a085;">Y:</strong> number of rows in each 2D array</li><li><strong style="color: #d35400;">Z:</strong> number of columns in each 2D array</li></ul></div>

In [14]:
a4=np.array([[[6,5,4,0,1,2,3,7,8,9,10,56]]])
print('====================')

print(a4.shape,'\n',a4.ndim)
print('====================')
print(a4.size)
print('====================')

print(a4.reshape(4,3))
print('====================')

A=a4.reshape(3,2,2)
print('====================')

print('A=',A)

print('====================')


(1, 1, 12) 
 3
12
[[ 6  5  4]
 [ 0  1  2]
 [ 3  7  8]
 [ 9 10 56]]
A= [[[ 6  5]
  [ 4  0]]

 [[ 1  2]
  [ 3  7]]

 [[ 8  9]
  [10 56]]]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 26px; margin: 0 0 15px 0;">Array Creation (Initialization)</h2><ul style="font-size: 16px; color: #333; line-height: 2;"><li><strong style="color: #6c3483;">Using List (Tuple)</strong></li><li><strong style="color: #2980b9;">Using NumPy Functions:</strong><ul style="margin-top: 8px; line-height: 1.9;"><li style="font-family: monospace; color: #444;">np.arange</li><li style="font-family: monospace; color: #444;">np.linspace</li><li style="font-family: monospace; color: #444;">np.zeros</li><li style="font-family: monospace; color: #444;">np.ones</li><li style="font-family: monospace; color: #444;">np.full</li><li style="font-family: monospace; color: #444;">np.eye</li><li style="font-family: monospace; color: #444;">np.random.random</li><li style="font-family: monospace; color: #444;">np.empty / np.empty_like</li></ul></li><li><strong style="color: #c2185b;">Using the Input Function</strong></li></ul></div>

In [15]:
# array creation using list(tuple)

list_arr=[1,2,3,4,5,6]
# tuple_arr=(5,6,7)
a=np.array(list_arr,dtype=int)
print('a array:',a,'\n','shape of the array a:',a.shape,'\n','dimension of a=',a.ndim)
b=np.array([[2,5,7],[9,0,3]])
print('b array:',b,'\n','shape of the array b:',b.shape,'\n','dimension of b=',b.ndim)
c=np.array([[[1,2]],[[3,4]]])
print('c array:',c,'\n','shape of the array c:',c.shape,'\n','dimension of c=',c.ndim)

a array: [1 2 3 4 5 6] 
 shape of the array a: (6,) 
 dimension of a= 1
b array: [[2 5 7]
 [9 0 3]] 
 shape of the array b: (2, 3) 
 dimension of b= 2
c array: [[[1 2]]

 [[3 4]]] 
 shape of the array c: (2, 1, 2) 
 dimension of c= 3


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 12px 0;">Array Creation Using NumPy Functions</h2><p style="font-size: 16px; color: #333; margin: 6px 0;">The <code style="background-color: #e0d0f5; color: #6c3483; padding: 2px 6px; border-radius: 4px;">numpy.linspace()</code> function is used to create an array of evenly spaced numbers within a specified range.</p><p style="font-size: 16px; color: #333; margin: 15px 0 8px 0;">It uses the following basic syntax:</p><p style="font-family: monospace; background-color: #e0d0f5; color: #2c3e50; padding: 8px 12px; border-radius: 6px; display: inline-block; font-size: 15px;">numpy.linspace(start, stop, num, ...)</p><p style="font-size: 16px; color: #333; margin: 15px 0 8px 0;">where:</p><ul style="font-size: 16px; color: #333; line-height: 1.9;"><li><strong style="color: #6c3483;">start:</strong> the starting value of the sequence</li><li><strong style="color: #2980b9;">stop:</strong> the end value of the sequence</li><li><strong style="color: #c2185b;">num:</strong> the number of values to generate</li></ul></div>

In [16]:
#using linspace function
#linspace(start, stop, no of sample points)

b=np.linspace(0,10,6)
print(b)


[ 0.  2.  4.  6.  8. 10.]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #fff2e6; border-left: 6px solid #d35400; border-radius: 6px; padding: 15px 20px;"><p style="font-size: 16px; color: #7a3d00; margin: 0;"><strong>Note:</strong> np.linspace allows you to define how many values you get, including the specified min and max value. It infers the step size automatically.</p></div>

In [19]:
#create 11 evenly spaced values b/w 0 and 20
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 12px 0;">The np.arange() Function</h2><p style="font-size: 16px; color: #333; margin: 6px 0 8px 0;">It uses the following basic syntax:</p><p style="font-family: monospace; background-color: #e0d0f5; color: #2c3e50; padding: 8px 12px; border-radius: 6px; display: inline-block; font-size: 15px;">np.arange(start, stop, step, ...)</p><p style="font-size: 16px; color: #333; margin: 15px 0 8px 0;">where:</p><ul style="font-size: 16px; color: #333; line-height: 1.9;"><li><strong style="color: #6c3483;">start:</strong> the starting value of the sequence</li><li><strong style="color: #2980b9;">stop:</strong> the end value of the sequence</li><li><strong style="color: #c2185b;">step:</strong> the spacing between values</li></ul></div>

<div style="font-family: 'Times New Roman', Times, serif; background-color: #fff2e6; border-left: 6px solid #d35400; border-radius: 6px; padding: 15px 20px;"><p style="font-size: 16px; color: #7a3d00; margin: 0;"><strong>Note:</strong> np.arange excludes the maximum value, unless rounding error causes it to behave otherwise.</p></div>

In [20]:
#create sequence of values between 0 and 20 where spacing is 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
#using arrange function
#arrange(start, stop, step size)

np.arange(0,10,3)

array([0, 3, 6, 9])

In [22]:
# Create an array of all zeros
a = np.zeros((2,2))
b = np.zeros((3,2),dtype='uint8')  # Create an array of all zeros having data type uint8(unsigned int)
c = np.zeros((2,2),dtype='float')  # Create an array of all zeros
print(a,'\n',b,'\n',c)

[[0. 0.]
 [0. 0.]] 
 [[0 0]
 [0 0]
 [0 0]] 
 [[0. 0.]
 [0. 0.]]


In [23]:
# Create an array of all ones
b = np.ones((1,2))
c=2*np.pi*np.ones((1,2))   # Create an array of all pi
print(b)
print(c)

[[1. 1.]]
[[6.28318531 6.28318531]]


In [24]:
# Create a constant array using full
#full(shape, fill_value, dtype=)
c = np.full((3,2), 90.6,dtype=int)
#c = np.full((2,2),50,dtype=int)
print(c)

[[90 90]
 [90 90]
 [90 90]]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 12px 0;">numpy.eye</h2><p style="font-family: monospace; background-color: #e0d0f5; color: #2c3e50; padding: 8px 12px; border-radius: 6px; display: inline-block; font-size: 14px;">numpy.eye(N, M=None, k=0, dtype=&lt;class 'float'&gt;)</p><p style="font-size: 16px; color: #333; margin: 15px 0;">Returns a 2D array with ones on the diagonal and zeros elsewhere.</p><ul style="font-size: 16px; color: #333; line-height: 2;"><li><strong style="color: #6c3483;">N</strong> <span style="color: #888; font-size: 14px;">(int):</span> number of rows in the output</li><li><strong style="color: #2980b9;">M</strong> <span style="color: #888; font-size: 14px;">(int, optional):</span> number of columns in the output. If None, defaults to N</li><li><strong style="color: #c2185b;">k</strong> <span style="color: #888; font-size: 14px;">(int, optional):</span> index of the diagonal. 0 refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal</li><li><strong style="color: #16a085;">dtype</strong> <span style="color: #888; font-size: 14px;">(data type, optional):</span> data type of the returned array</li></ul></div>

In [25]:
# Create a 2x2 identity matrix
#eye(rows, columns, k=0, dtype)
# main diagonal
a=np.eye(2,2,0)
print("Diagonal matrix:\n",a)
# upper diagonal
a1=np.eye(4,4,2)
print("Upper diagonal matrix:\n",a1)
# lower diagonal
a2=np.eye(2,2,-1)
print("Lower Diagonal matrix:\n",a2)

d=2*np.eye(4,4,-1)+3*np.eye(4,4,1)
print("4x4 matrix with diagonal entries zeros:\n",d)

Diagonal matrix:
 [[1. 0.]
 [0. 1.]]
Upper diagonal matrix:
 [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Lower Diagonal matrix:
 [[0. 0.]
 [1. 0.]]
4x4 matrix with diagonal entries zeros:
 [[0. 3. 0. 0.]
 [2. 0. 3. 0.]
 [0. 2. 0. 3.]
 [0. 0. 2. 0.]]


In [26]:
d=2*np.eye(4,4,-1)+3*np.eye(4,4,1)+4*np.eye(4,4,0)
print("4x4 matrix with diagonal entries zeros:\n",d)

4x4 matrix with diagonal entries zeros:
 [[4. 3. 0. 0.]
 [2. 4. 3. 0.]
 [0. 2. 4. 3.]
 [0. 0. 2. 4.]]


In [27]:
# Create an array filled with random values
import numpy as np
#e = np.random.random((2,3))
#print(e)
#f=np.random.random((20))
#print(f)
g=np.random.random((1,3,2))
print(g)

[[[0.82196448 0.28137829]
  [0.56087353 0.79451472]
  [0.62367264 0.96386359]]]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 10px 0;">Split()</h2><p style="font-size: 16px; color: #333; margin: 6px 0;">Splitting is the reverse operation of joining.</p><p style="font-size: 16px; color: #333; margin: 6px 0;">Joining merges multiple arrays into one, while splitting breaks one array into multiple arrays.</p></div>

In [28]:
# splitting the array
arr=np.array([1,5,6,9,7,4,3,2])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 5]), array([6, 9]), array([7, 4]), array([3, 2])]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 12px 0;">The map() Function</h2><p style="font-size: 16px; color: #333; margin-bottom: 12px;">The <code style="background-color: #e0d0f5; color: #6c3483; padding: 2px 6px; border-radius: 4px;">map()</code> function takes two parameters, a function name and an iterable.</p><ul style="font-size: 16px; color: #333; line-height: 2;"><li><strong style="color: #6c3483;">Function name:</strong> the particular function to be applied on each value</li><li><strong style="color: #2980b9;">Iterable:</strong> the list of values on which the function must be applied</li></ul><p style="font-size: 16px; color: #333; margin-top: 12px;">The <code style="background-color: #e0d0f5; color: #6c3483; padding: 2px 6px; border-radius: 4px;">map()</code> function returns a list of values on which the specified function has been applied.</p></div>

In [29]:
# define map function in first lecture.It is very important.
def my_func(x,y):
     return x+y**2-2
z=map(my_func,(22,-3),(3,-4))
print(list(z))

[29, 11]


In [30]:
#please add map function in lecture 1. its very important function
def my_func(x,y):
    return x+y
z=map(my_func,(2,3),(3,4))
print(list(z)) #?

[5, 7]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 12px 0;">Functions in NumPy</h2><p style="font-size: 16px; color: #333; margin-bottom: 10px;">Some of the functions are as follows:</p><ul style="font-size: 16px; color: #333; line-height: 2; font-family: monospace;"><li>reshape()</li><li>flatten()</li><li>ravel()</li><li>trace()</li><li>transpose()</li></ul></div>

In [32]:
# how to use reshape function
a=np.arange(0,12,2)
print(a)
b=a.reshape(2,3)
print(b)
# in one line
a=np.arange(0,12,2).reshape(2,3)
print(a)

[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  2  4]
 [ 6  8 10]]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 22px; margin: 0 0 8px 0; font-family: monospace;">flatten()</h2><p style="font-size: 16px; color: #333; margin: 0;">Returns a copy of the array collapsed into one dimension.</p></div>

In [33]:
a=np.arange(10).reshape(2,5)
print(a)
b=a.flatten()
print(b)
b[4]=100
print(b)
#acopy of a
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3 100   5   6   7   8   9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 22px; margin: 0 0 8px 0; font-family: monospace;">ravel()</h2><p style="font-size: 16px; color: #333; margin: 0;">Returns a contiguous flattened array.</p></div>

In [34]:
# to get a 1 dim array by applying reval function
a=np.arange(10).reshape(2,5)
b=a.ravel()
print(b)
b[0]=100
print(b)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[[100   1   2   3   4]
 [  5   6   7   8   9]]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #fff2e6; border-left: 6px solid #d35400; border-radius: 6px; padding: 15px 20px;"><p style="font-size: 16px; color: #7a3d00; margin: 0 0 8px 0;"><strong>Note:</strong> ravel() is faster than flatten() since it does not occupy any additional memory.</p><p style="font-size: 16px; color: #7a3d00; margin: 0;">flatten() is comparatively slower than ravel() since it occupies memory.</p></div>

<h2 style="font-family: 'Times New Roman', Times, serif; color: #2c3e50; font-weight: bold; font-size: 26px;">Arithmetic Operations</h2>

In [36]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b) # manually
print(np.add(a,b)) # by built in function
# Subtraction:
print(a-b) # manually
print(np.subtract(a,b)) # by built in function
# Multiplication
print(a*b) # manually
print(np.multiply(a,b)) # by built in function
# Division:
print(a/b) # manually
print(np.divide(a,b)) # by built in function
## Power:
print(a**2) # manually
print(np.power(a,2)) # by built in function
#remainder:
print(a%b) # manually
print(np.mod(a,b)) # by built in function
print(np.mod(b,a)) # by built in function

# Transpose:
print("Transpose:",a.T)


[5 7 9]
[5 7 9]
[-3 -3 -3]
[-3 -3 -3]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[1 4 9]
[1 4 9]
[1 2 3]
[1 2 3]
[0 1 0]
Transpose: [1 2 3]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 10px 0;">Linear Algebra Functions</h2><p style="font-size: 16px; color: #333; margin: 0;">For matrix multiplication, the function <code style="background-color: #e0d0f5; color: #6c3483; padding: 2px 6px; border-radius: 4px;">np.matmul()</code> is used.</p></div>

In [37]:
import numpy as np
## For Matrix Multiplication:
A=np.array([[[1,2], [3,4]]])
B=np.array([[[3,4], [3,7]]])

print(A.shape)
C=np.matmul(A,B)
print(C)
print("Inverse:",np.linalg.inv(A))   ## Inverse
print("Determinant:",np.linalg.det(A))   ## determinant
print("Eigen Values:",np.linalg.eig(A))   ## eigen values



(1, 2, 2)
[[[ 9 18]
  [21 40]]]
Inverse: [[[-2.   1. ]
  [ 1.5 -0.5]]]
Determinant: [-2.]
Eigen Values: EigResult(eigenvalues=array([[-0.37228132,  5.37228132]]), eigenvectors=array([[[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]]))


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 25px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 26px; margin: 0 0 15px 0;">Array Indexing</h2><p style="font-size: 16px; color: #333; margin: 8px 0;">Indexing refers to the process of accessing individual elements or a subset of elements from a data structure, such as an array, list, or string, using a unique identifier known as an index.</p><p style="font-size: 16px; color: #333; margin: 8px 0;">The index refers to the position of an element within the structure, allowing it to be retrieved or modified directly.</p><p style="font-size: 16px; color: #333; margin: 8px 0;">In most programming contexts, indexing is zero based, meaning the first element is accessed using index 0.</p><p style="font-size: 16px; color: #333; margin: 8px 0;">In a one dimensional array, a single index is used, while in multi dimensional arrays, multiple indices are needed to specify the position of an element along each dimension.</p><p style="font-size: 17px; font-weight: bold; color: #6c3483; margin-top: 15px;">1D Array Indexing</p></div>

In [38]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # Output: 10
print(arr[3])  # Output: 40
print(arr[-1])
f=arr[0]=3# Output: 50 (negative indexing starting from the back of the array)
print(f)

10
40
50
3


In [39]:
arr=np.array([[1,2,3,4],
              [5,62,1,2],
              [5,8,1,0]])
arr[1,2]=5 #if we want to
print(arr)
#print(arr[2,3])

[[ 1  2  3  4]
 [ 5 62  5  2]
 [ 5  8  1  0]]


<h2 style="font-family: 'Times New Roman', Times, serif; color: #2c3e50; font-weight: bold; font-size: 24px;">Array Indexing: Examples</h2>

In [40]:
a=np.array([[1,2,3],[5,6,7],[4,0,1]])
a[1,1]
a[1,1]=9999
print(a)
print('==========================')

print('bbbb',a[:2])
print('==========================')

print(a[:2])
print('==========================')
print(a[1:])
# To print [3,9999,1]
print('==========================')

print('Required ele',[a[0,2],a[1,1],a[2,2]])

[[   1    2    3]
 [   5 9999    7]
 [   4    0    1]]
bbbb [[   1    2    3]
 [   5 9999    7]]
[[   1    2    3]
 [   5 9999    7]]
[[   5 9999    7]
 [   4    0    1]]
Required ele [3, 9999, 1]


<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 20px 30px;"><h2 style="color: #2c3e50; font-weight: bold; font-size: 24px; margin: 0 0 10px 0;">Boolean Indexing</h2><p style="font-size: 16px; color: #333; margin: 6px 0;">Boolean array indexing lets you pick out arbitrary elements of an array.</p><p style="font-size: 16px; color: #333; margin: 6px 0;">Frequently, this type of indexing is used to select the elements of an array that satisfy some conditions. Here is an example:</p></div>

In [41]:
a=np.array([1,6,8,0,2,5,7,8,3,4,9])
bool_index=(a > 4)
print(bool_index)
print(a[bool_index])


[False  True  True False False  True  True  True False False  True]
[6 8 5 7 8 9]


In [42]:
myli=[0,3,5,7,2,1,8]
print(myli[:4])
print(myli[:-3])
print(myli[:1:-3])

[0, 3, 5, 7]
[0, 3, 5, 7]
[8, 7]


<div style="text-align: center; background: linear-gradient(135deg, #e8d5f5, #d0e8fb); border-radius: 16px; padding: 25px 30px; font-family: 'Times New Roman', Times, serif;"><h1 style="font-size: 30px; font-weight: bold; color: #2c3e50; margin: 0;">Home Tasks</h1></div>

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 18px 25px;"><p style="font-size: 18px; font-weight: bold; color: #6c3483; margin: 0 0 8px 0;">Question 01</p><p style="font-size: 16px; color: #333; margin: 0;">Create an array of dimension three, having 2 two dimensional arrays, each of which has 1 row and four columns.</p></div>

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 18px 25px;"><p style="font-size: 18px; font-weight: bold; color: #6c3483; margin: 0 0 8px 0;">Question 02</p><p style="font-size: 16px; color: #333; margin: 0;">Create a one dimensional array using a built in function and split it into 3 parts.</p></div>

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 18px 25px;"><p style="font-size: 18px; font-weight: bold; color: #6c3483; margin: 0 0 8px 0;">Question 03</p><p style="font-size: 16px; color: #333; margin: 0;">Find the eigenvalues of a matrix of order four.</p></div>

<div style="font-family: 'Times New Roman', Times, serif; background-color: #f5f0ff; border-left: 8px solid #6c3483; border-radius: 8px; padding: 18px 25px;"><p style="font-size: 18px; font-weight: bold; color: #6c3483; margin: 0 0 8px 0;">Question 04</p><p style="font-size: 16px; color: #333; margin: 0;">If <code style="background-color: #e0d0f5; color: #6c3483; padding: 2px 6px; border-radius: 4px;">np.array([[[2,3,5]],[[6,7,8]],[[1,7,3]],[[5,5,5]]])</code> is an array, specify its features and apply boolean indexing.</p></div>